USE [database-1]
GO

CREATE  PROCEDURE dbo.P111
    @Param1  UNIQUEIDENTIFIER,
    @param2  NVARCHAR(100) OUTPUT
WITH EXECUTE AS OWNER
AS EXTERNAL NAME A.B.C

GO 

CREATE TABLE Table1
(
    Id INT IDENTITY(1, 1) PRIMARY KEY,
    Column2 NVARCHAR(100) NOT NULL,
    Column3 NVARCHAR(100) NOT NULL,
    Column4 VARCHAR(100) NOT NULL,
    Column5 VARCHAR(100) NOT NULL,
    CreatedAt DATETIME NOT NULL
);
